# 데이터 분석에 필요한 도구를 배워보겠습니다!

### pandas, numpy

- numpy : 연산에 관련된 라이브러리
- pandas : 수치 통계와 관련된 라이브러리

In [1]:
# 판다스 도구 불러오기  as:별명, 별칭
import pandas as pd

In [129]:
# pd.read_csv('파일의 저장경로/파일명.확장자명')
# pd.read_csv('C:/Users/kj/Desktop/Pokemon.csv')

df = pd.read_csv('Pokemon.csv')

df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [15]:
df.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

In [16]:
df.tail(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [19]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [21]:
df.shape

(800, 13)

### 판다스 데이터 확인

- df.head(n) : 상위 n개(비웠을 때 5개)의 데이터만 보겠다.
- df.tail() : 하위 5개의 데이터만 보겠다.
- df.info() : 컬럼명, 결측치 여부, 데이터 타입
- df.describe() : 숫자형 데이터의 통계량 (평균, 표준편차, 사분위수)
  이상치 --> 정규화(가장 일반적인 정규화 방법으로, 각 데이터를 최소값을 0, 최대값을 1로 변환), 표준화(데이터를 평균이 0 표준 편차가 1이 되도록 변환하는 과정)
- df.shape() : 데이터의 행과 열 크기

### 판다스 기본 구조

- 크게 두 가지 자료구조를 가진다

- 1. 시리즈 : 1차원 배열 형태(엑셀 : 열 한 개)
  2. 데이터 프레임(df) : 2차원 표 형태(시리즈가 여러 개 모인 것)

In [22]:
df.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

In [23]:
df['Type 1']

0        Grass
1        Grass
2        Grass
3        Grass
4         Fire
        ...
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, Length: 800, dtype: object

In [25]:
df[['Type 1','Name']]

      Type 1                   Name
0      Grass              Bulbasaur
1      Grass                Ivysaur
2      Grass               Venusaur
3      Grass  VenusaurMega Venusaur
4       Fire             Charmander
..       ...                    ...
795     Rock                Diancie
796     Rock    DiancieMega Diancie
797  Psychic    HoopaHoopa Confined
798  Psychic     HoopaHoopa Unbound
799     Fire              Volcanion

[800 rows x 2 columns]

In [33]:
ㅋㅋㅋ = '안녕하세요'
#하세만 출력
ㅋㅋㅋ[2:4]

'하세'

In [36]:
df.loc[100:200,'Name':'Total']

                      Name    Type 1  Type 2  Total
100                Haunter     Ghost  Poison    405
101                 Gengar     Ghost  Poison    500
102      GengarMega Gengar     Ghost  Poison    600
103                   Onix      Rock  Ground    385
104                Drowzee   Psychic     NaN    328
..                     ...       ...     ...    ...
196  AmpharosMega Ampharos  Electric  Dragon    610
197              Bellossom     Grass     NaN    490
198                 Marill     Water   Fairy    250
199              Azumarill     Water   Fairy    420
200              Sudowoodo      Rock     NaN    410

[101 rows x 4 columns]

In [37]:
df.loc[100:200,['Name','Total']]

                      Name  Total
100                Haunter    405
101                 Gengar    500
102      GengarMega Gengar    600
103                   Onix    385
104                Drowzee    328
..                     ...    ...
196  AmpharosMega Ampharos    610
197              Bellossom    490
198                 Marill    250
199              Azumarill    420
200              Sudowoodo    410

[101 rows x 2 columns]

In [43]:
df.iloc[0:4,1:3]

                    Name Type 1
0              Bulbasaur  Grass
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass

### 데이터의 선택 및 필터링

- 열 선택 : df['컬럼명'] / df[['컬럼명1','컬럼명2']]
- 행 선택 : loc / iloc
- df.loc[이름] : 인덱스 이름을 기준으로 행 선택
- df.iloc[번호] : 정수 인덱스 번호를 기준으로 행 선택
-

In [38]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [49]:
# Total이 500보다 큰 데이터만 출력

df[ df['Total']>500 ]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [73]:
# Type 1에서 fire와 water만     or = |

df[ (df['Type 1'] == 'Fire') |  (df['Type 2'] == 'Water') ]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
758,688,Binacle,Rock,Water,306,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,500,72,105,115,54,86,68,6,False
760,690,Skrelp,Poison,Water,320,50,60,60,60,60,30,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [82]:
df[ (df['Type 1'] == 'Fire') &  (df['Type 2'] == 'Flying') ]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False

# 데이터 전처리(Cleaning)

- 결측치 처리
- df.isnull().sum() : 결측치 개수가 몇 개인지 확인
- df.dropna() : 결측치가 있는 행/열을 삭제
- df['컬럼명'].fillna(값) : 결측치를 특정 값으로 채운다.

- 정렬
- df.sort_values(by = '컬럼명', ascending = True/False)

- 데이터 변형
- df['기존에 없는 컬럼명'] = df['Total'] * 10

- 데이터 지우기
- df.drop(['컬럼명'], axis = 1) 0가로 1세로. 가로는 loc,iloc 써서.

In [76]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [79]:
df_drop = df.dropna()

In [80]:
df_drop

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [81]:
# df.dropna(inplace=True)
# df = df.dropna()

In [84]:
df.sort_values(by = 'Name', ascending = True)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [85]:
df['Total_10'] = df['Total'] * 10
df.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_10
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,3180

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_10
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,3180

In [89]:
df. drop(['Total_10'], axis =1, inplace=True)

In [90]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

--------------------------------------------

In [92]:
df.groupby('Type 1')['Total'].mean()

Type 1
Bug         378.927536
Dark        445.741935
Dragon      550.531250
Electric    443.409091
Fairy       413.176471
Fighting    416.444444
Fire        458.076923
Flying      485.000000
Ghost       439.562500
Grass       421.142857
Ground      437.500000
Ice         433.458333
Normal      401.683673
Poison      399.142857
Psychic     475.947368
Rock        453.750000
Steel       487.703704
Water       430.455357
Name: Total, dtype: float64

# 데이터의 집계 및 병합

***
- 그룹화 : 특정 기준에 따라 데이터를 묶어 통계
- ex) df.groupby('성별')['점수'].mean()
- 성별에 따른 점수 평균

In [93]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [100]:
# Type1이 Fire이면서 speed가 100 이상인 포켓몬의 이름과 Total 점수만 출력

df.loc[(df['Type 1']=='Fire') & (df['Speed']>=100),['Name', 'Total']]

                          Name  Total
6                    Charizard    534
7    CharizardMega Charizard X    634
8    CharizardMega Charizard Y    634
43                   Ninetales    505
84                    Rapidash    500
171                 Typhlosion    534
263                      Entei    580
279      BlazikenMega Blaziken    630
437                  Infernape    534
573                   Simisear    498
723                    Delphox    534
731                 Talonflame    499
736                     Pyroar    507

In [101]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [118]:
# 포켓몬의 물리 공격력과 특수 공격력 중 더 높은 값을 선택하여 Max_attack 이라는 칼럼을 만들어주세요

df['Max_attack'] = df[['Attack', 'Sp. Atk']].max(axis = 1)

In [119]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Max_attack
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,65
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,80
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,100
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,122
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,100
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,160
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,150
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,170
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,130

In [136]:
#'Total' 점수가 높은 순서대로 내림차순 정렬하되, 
# 점수가 같다면 'Name'을 알파벳 순으로 오름차순 정렬하여, 상위 10개 행만 출력하세요

df.sort_values(by = ['Total','Name'], ascending = [False,True]).head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True

In [137]:
df.groupby('Type 1').size()

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
dtype: int64

In [140]:
df.groupby('Type 1')['Total'].agg(['mean','min','max'])

                mean  min  max
Type 1
Bug       378.927536  194  600
Dark      445.741935  220  680
Dragon    550.531250  300  780
Electric  443.409091  205  610
Fairy     413.176471  218  680
Fighting  416.444444  210  625
Fire      458.076923  250  680
Flying    485.000000  245  580
Ghost     439.562500  275  680
Grass     421.142857  180  630
Ground    437.500000  265  770
Ice       433.458333  250  580
Normal    401.683673  190  720
Poison    399.142857  245  535
Psychic   475.947368  198  780
Rock      453.750000  280  700
Steel     487.703704  300  700
Water     430.455357  200  770

In [152]:
df.groupby(['Type 1','Legendary'])['Defense'].agg(['mean','size'])

                          mean  size
Type 1   Legendary
Bug      False       70.724638    69
Dark     False       68.689655    29
         True        92.500000     2
Dragon   False       78.150000    20
         True       100.083333    12
Electric False       65.425000    40
         True        75.000000     4
Fairy    False       63.875000    16
         True        95.000000     1
Fighting False       65.925926    27
Fire     False       64.531915    47
         True        98.200000     5
Flying   False       57.500000     2
         True        75.000000     2
Ghost    False       79.266667    30
         True       110.000000     2
Grass    False       70.283582    67
         True        82.333333     3
Ground   False       79.821429    28
         True       120.000000     4
Ice      False       68.818182    22
         True       100.000000     2
Normal   False       58.697917    96
         True       115.000000     2
Poison   False       68.821429    28
Psychic  False       61.000000    43
         True        88.214286    14
Rock     False       97.125000    40
         True       137.500000     4
Steel    False      126.652174    23
         True       124.750000     4
Water    False       71.990741   108
         True        98.750000     4

# 기본 그룹화 : groupby() + 집계함수

sum / count / size

- df.groupby('Type 1').mean()
- df.groupby('Type 1').size() : type 1 별로 포켓몬이 몇마리씩 있는지 출력

# 여러 개의 집계를 한번에 하는 방법

- df.groupby('Type 1').agg(['mean','min','max'])

# 다중 인덱스 그룹화
ex) Type1뿐만아니라 전설의 여부까지 포함해서 그룹화

- df.groupby(['Type 1','Legendary'])['Defense'].mean

In [143]:
# 가장 강한 타입 찾기 내림차순으로 정렬

df.groupby('Type 1')['Total'].mean().sort_values(ascending=False)

Type 1
Dragon      550.531250
Steel       487.703704
Flying      485.000000
Psychic     475.947368
Fire        458.076923
Rock        453.750000
Dark        445.741935
Electric    443.409091
Ghost       439.562500
Ground      437.500000
Ice         433.458333
Water       430.455357
Grass       421.142857
Fighting    416.444444
Fairy       413.176471
Normal      401.683673
Poison      399.142857
Bug         378.927536
Name: Total, dtype: float64

In [146]:
# 세대 별 포켓몬 수
df.groupby('Generation').size()

Generation
1    166
2    106
3    160
4    121
5    165
6     82
dtype: int64

In [147]:
# 타입 별 체력의 총 합

df.groupby('Type 1')['HP'].sum()

Type 1
Bug         3925
Dark        2071
Dragon      2666
Electric    2631
Fairy       1260
Fighting    1886
Fire        3635
Flying       283
Ghost       2062
Grass       4709
Ground      2361
Ice         1728
Normal      7573
Poison      1883
Psychic     4026
Rock        2876
Steel       1761
Water       8071
Name: HP, dtype: int64

In [151]:
# 전설의 포켓몬의 타입 별 분포

df[df['Legendary'] == True].groupby('Type 1').size().sort_values(ascending=False)

Type 1
Psychic     14
Dragon      12
Fire         5
Electric     4
Ground       4
Rock         4
Steel        4
Water        4
Grass        3
Dark         2
Flying       2
Ghost        2
Ice          2
Normal       2
Fairy        1
dtype: int64